# Change these first
owner: n2o-bot # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Nextcloud
    url: https://cloudy.cmeter.de
  - name: Arnold Horsch e.K.
    url: https://arnold-horsch.de
  - name: Senne Archiv
    url: https://sennearchiv.de
  - name: IG Hasten
    url: https://ighasten.de
  - name: Blumen Röttger
    url: https://blumen-roettger.de
  - name: GUHEMA
    url: http://guhema.de
  - name: Bohm Bedachungen
    url: https://bohm-bedachungen.de
    
assignees:
  - n2o

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.meter.ninja
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: dark
  introTitle: "Status Page"
  introMessage: Check status of services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
